### ISSUE TITLE
examples have failed.

### ISSUE THREAD

**Issue by dunamist** [keystone-enclave/keystone#211] opened 2020-09-28 06:38 UTC
Hello! I followed this tutorial( http://docs.keystone-enclave.org/en/latest/Getting-Started/Tutorials/Build-Enclave-App-Hello-World-Native.html ). After I ran "make image" and booted qemu, I found hello-native.ke's locaton is "/", not "/root", then I copied it into "/root", but I just can't run it. This also happend when I ran hello.ke, but this time, I copied the whole directory into overlay, but the result is the same. So, please tell me how to fix it? Thanks a lot.
It's the master branch.
![微信图片_20200928123720](https://user-images.githubusercontent.com/56823964/94398475-2dcd0600-0198-11eb-88f2-43e930e0bb0e.png)
![微信图片_20200928123824](https://user-images.githubusercontent.com/56823964/94398479-302f6000-0198-11eb-99e7-4d838a388961.png)
![微信图片_20200928123728](https://user-images.githubusercontent.com/56823964/94398481-31608d00-0198-11eb-98b2-c17597b5f80f.png)

**Comment by dayeol** [comment] 2020-09-29 01:12
Could you try to uncompress the package and see what's inside?
```
./hello-native.ke --target <directory> --noexec
```
This will uncompress the binaries to <directory>.
Let me know what's in there.
Also, please uncompress it in the overlay and use `file` command to see if they are all RISC-V binaries.

**Comment by dunamist** [comment] 2020-09-29 12:26
OK! Here you are. That's very weird.

![微信截图_20200929202007](https://user-images.githubusercontent.com/56823964/94558013-fb073880-0291-11eb-8924-ce9b65c8ab43.png)
![微信截图_20200929202413_WPS图片](https://user-images.githubusercontent.com/56823964/94558018-fcd0fc00-0291-11eb-859e-7083b6de18e2.png)

**Comment by dayeol** [comment] 2020-09-29 19:23
Could you try manually running the enclave as follows:
```
./hello-runner hello eyrie-rt
```

**Comment by dunamist** [comment] 2020-09-30 02:01
OK! And this is really weird!
![微信截图_20200930095337_WPS图片](https://user-images.githubusercontent.com/56823964/94634843-c207ac00-0303-11eb-9918-e30244f30a53.png)
![微信截图_20200930095902](https://user-images.githubusercontent.com/56823964/94634883-e19ed480-0303-11eb-93c2-3b63f12f6001.png)

**Comment by dayeol** [comment] 2020-09-30 19:47
it seems to be `makeself` version issue. They have changed the stripping rule, and you're using an old version of makeself.
In old versions, they treat the entire command `./hello-runner hello eyrie-rt` as a single-word command, thus fails to execute the enclave properly.

I will see if we can fix this, but meanwhile, you can use later version of `makeself` 
Are you on Ubuntu 16.04?

**Comment by dunamist** [comment] 2020-10-12 02:28
No, I use Ubuntu 18.04.

**Comment by dunamist** [comment] 2020-10-12 03:04
the version of makeself is 2.3.0

**Comment by dayeol** [comment] 2020-10-19 21:05
I see, your makeself is actually newer than mine (2.2.0). I'll try to reproduce it

**Comment by dayeol** [comment] 2020-10-19 21:47
Could you also let me know what is your CMake version?

**Comment by atakanozyapici** [comment] 2020-11-11 06:56
I have the exact same issue. hello.ke does not run correctly, but when I manually run the enclave it prints the expected message. Indeed it is really weird, I couldn't solve why it doesn't run either. Also my makeself version is 2.3.0. My cmake version is 3.10.2. OS version is Ubuntu 18.04. I uncompressed tests.ke, the image is below. (tests.ke runs without any errors). 
![keystone](https://user-images.githubusercontent.com/36217653/98778583-3714d980-23b8-11eb-9054-7c06c3926de2.png)

**Comment by Praveen035** [comment] 2020-12-10 04:40
Right now, i facing exact same issue this issue is fixed or still it there @atakanozyapici @dayeol

**Comment by Praveen035** [comment] 2020-12-10 04:44
Right now,i am facing exact same issue it is fixed or still exist @atakanozyapici  @dayeol if it fixed can you please tell me how can i fix this issue.

**Comment by PLUS035** [comment] 2020-12-10 04:46
Right now,i am facing exact same issue it is fixed or still exist @atakanozyapici  @dayeol if it fixed can you please tell me how can i fix this issue.

**Comment by dayeol** [comment] 2020-12-11 01:29
This is because of a wrong script being passed to Makeself.
When we run makeself, we pass in the command "./hello-runner hello eyrie-rt" as a script to run after decompressing the package.
This is actually a command "./hello-runner" with two arguments "hello" and "eyrie-rt".
However, makeself treats the entire string as a single command (including the white space), executing "./hello-runner\ hello\ eyrie-rt", and since there's no such file like that, it errors.
This should be fixed via changing CMake macro to pass in correct command

**Comment by dayeol** [comment] 2020-12-11 01:54
This SDK PR will fix the issue.
https://github.com/keystone-enclave/keystone-sdk/pull/65

**Comment by PLUS035** [comment] 2020-12-11 07:46
Even after changing  macro.cmake file still i am getting same issue @dayeol.

**Closed** 2021-01-04 01:26 UTC
Labels: Bug
