### ISSUE TITLE
Fix for build issue with OpenSSL 1.1.0

### ISSUE THREAD

**Issue by pramodsu** [keystone-enclave/keystone#95] opened 2019-06-11 18:12 UTC
I was having trouble building the dev branch on Ubuntu 18.04. It seems like the problem is that Ubuntu 18.04 uses OpenSSL version 1.1.0 and this version of OpenSSL has removed some functions from their API, which causes the compilation of riscv-linux/scripts/extract-cert.c to fail.

The fix is pretty straightforward, a couple of initialization calls need to removed for OpenSSL version 1.1.0. (I got this information from the OpenSSL wiki: https://wiki.openssl.org/index.php/Library_Initialization.)

Here is the patch. I didn't submit a pull request because I wasn't sure where to submit it as riscv/riscv-linux is no longer maintained.

```
diff --git a/scripts/extract-cert.c b/scripts/extract-cert.c
index b071bf476fea..407ba4ad6352 100644
--- a/scripts/extract-cert.c
+++ b/scripts/extract-cert.c
@@ -91,8 +91,10 @@ int main(int argc, char **argv)
 {
        char *cert_src;
 
+#if OPENSSL_VERSION_NUMBER < 0x10100000L
        OpenSSL_add_all_algorithms();
        ERR_load_crypto_strings();
+#endif
        ERR_clear_error();
 
        kbuild_verbose = atoi(getenv("KBUILD_VERBOSE")?:"0");
```

I thought I'd create an issue so that you guys can either apply the patch or document the issue somewhere.

**Comment by dkohlbre** [comment] 2019-06-11 18:24
Thanks for the report.
The right answer is that we move up to mainline, rather than rely on the now-deprecated riscv-linux.

I'll see if we can move to mainline asap, otherwise we'll switch to our fork of riscv-linux and apply your patch temporarily.

**Comment by dkohlbre** [comment] 2019-06-13 21:48
Moving to mainline is not immediately feasible: we'll need to re-write and upstream some patches from riscv-linux that never landed. This may need to happen at the same time as global move to mainline qemu and bumping riscv-pk at the same time, as there are compatibility issues all over.

I'll be using your patch and adding it to our build process for patching our existing usage of riscv-linux.

**Comment by dkohlbre** [comment] 2019-06-13 22:57
If you get a chance, can you confirm what your build system's openssl, kernel, and distro versions were?
I'm running openssl 1.1.1, kernel 4.15, and Ubuntu 18.04 but can't reproduce the build failure.

**Comment by pramodsu** [comment] 2019-06-14 05:55
I realized that I am actually using LibreSSL v2.9.0 and not OpenSSL which is probably the cause of these. Sorry about the confusion! I'd forgotten that I'd installed LibreSSL at some point in the past.

My kernel version is 4.15.0 and the distro version is 18.04.2.

**Comment by dkohlbre** [comment] 2019-06-14 16:40
Not a problem, we actually had a report from someone else about issues with openssl and builds.
For now I'm going to close the issue since it appears this one was LibreSSL related.
Please feel free to open up a new one if you run into any other build issues.

**Closed by dkohlbre** 2019-06-14 16:40 UTC
