### ISSUE TITLE
CMake Error and Kernel Panic in SiFive FU540

### ISSUE THREAD

**Issue by wangaixue** [keystone-enclave/keystone#189] opened 2020-06-15 09:58 UTC
I want to build in fu540. My command is
mkdir build
cd build
cmake  ..  -DLINUX_SIFIVE=y 

But I meet the error 

CMake Error: The inter-target dependency graph contains the following strongly connected component (cycle):
  "buildroot" of type UTILITY
    depends on "image-deps" (strong)
  "sm" of type UTILITY
    depends on "linux" (strong)
  "linux" of type UTILITY
    depends on "sysroot" (strong)
  "driver" of type UTILITY
    depends on "linux" (strong)
  "sysroot" of type UTILITY
    depends on "buildroot" (strong)
  "image-deps" of type UTILITY
    depends on "sm" (strong)
    depends on "driver" (strong)
At least one of these targets is not a STATIC_LIBRARY.  Cyclic dependencies are allowed only among static libraries.
CMake Generate step failed.  Build files cannot be regenerated correctly.

can you give me some advices

**Comment by dkohlbre** [comment] 2020-06-15 18:21
Can you check what branch/version of Keystone you are on?
This was an issue a little while ago, but was fixed in the `dev` branch.

In general, it helps us a lot if you fill out the bug report form, since it asks for the output of `git submodule status` and what branch you are using.

**Comment by wangaixue** [comment] 2020-06-16 02:05
@dkohlbre I use the command "git branch " to check what branch /version of  keystone. The result is *master. I also git clone -b dev  https://github.com/keystone-enclave/keystone to get the dev branch.
I also use command "git submodule status" . The result is 

1fcdfbfb8a28b81283575efc3faa92ce4a0d4e56 buildroot (2019.08)
 4d856f72c10ecb060868ed10ff1b1453943fc6c8 linux (v5.3)
 f0a54554cdba482b5ac6586e8b691771e83427d6 linux-keystone-driver (f0a5455)
 9e06029aea3b2eca1d5261352e695edc1e7d7b8b qemu (v4.1.0)
 1b80cbe97d2c29212398d3b74ddc54718ad32e23 riscv-gnu-toolchain (v20171231-6-g1b80cbe)
 5b3d7151daa509ba0c2b330323208823abce324a riscv-pk (archive-1.9.1-259-g5b3d715)
 7c3fcf0eb499508cf582fd9b550d3a5f0d587dff sdk (remotes/origin/dev-dyn-alloc-33-g7c3fcf0)

**Comment by dkohlbre** [comment] 2020-06-16 02:26
Please try the `dev` branch.

**Comment by wangaixue** [comment] 2020-06-16 02:29
@dkohlbre  ok, I will try the dev branch. Thanks very much.

**Comment by wangaixue** [comment] 2020-06-19 03:11
@dkohlbre  ok. The dev branch is very nice.  And the output.log is same with the expected.log. 
I also build successfully in hifive unleashed and get the bbl.bin. And then compile https://github.com/keystone-enclave/freedom-u540-c000-bootloader to get the fsbl.bin. Finally, I follow the shell script to partition SD card , dd the bbl.bin to /dev/sdb1 ,dd the fsbl.bin to /dev/sdb4. But when I  launch development board of fu540，it no response.  I also use piscocom to get the ternimal it also no rensponse. can you give me some advice ??Can you tell me how to test the all keystone systerm or if it just like in qemu. 
Thanks very much!!!!!
best wishes!!

**Comment by wangaixue** [comment] 2020-06-19 13:03
@dkohlbre  At the same time, when I test my build in hifive unleashed, I meet the problem :

1.687435]  t5 : ffffffe000cc0940 t6 : ffffffe000cc0140
[    1.687706] sstatus: 0000000000000120 sbadaddr: ffffffd004000000 scause: 000000000000000d
[    1.688627] ---[ end trace b4688d94a9846d98 ]---
[    1.689114] Kernel panic - not syncing: Attempted to kill init! exitcode=0x0000000b
[    1.689615] ---[ end Kernel panic - not syncing: Attempted to kill init! exitcode=0x0000000b ]---

the building processing is:
cmake .. -DLINUX_SIFIVE=y
make 
make image 
And then  test./scripts/run-qemu.sh
I also use this bbl.bin in development board of fu540, And meet the same problem. can you help me cheak the problem. 
Thanks!!!

**Comment by dkohlbre** [comment] 2020-06-19 22:20
a `cmake .. -DLINUX_SIFIVE=y` build should work for both qemu and on the hifive.
My guess is that the build wasn't fully cleaned after you switched branches.
Try removing `build/` and reverting any applied patches to the Linux submodule. (Go to the Linux submodule and git reset --hard)

**Comment by wangaixue** [comment] 2020-06-20 13:38
@dkohlbre I am sorry to disturb you. very sorry!!! 
To prevent the build wasn't  wasn't fully cleaned after you switched branches. I download the code and  rebuild the keystone. The process are as follows, can you give me some advices?
My systerm is ubuntu 18.04, gcc and g++ version are 7.5

(1) Firstly, I git clone the dev branch.
git clone -b dev   https://github.com/keystone-enclave/keystone
(2) install dependences .... The packages are all install successfully
(3) install riscv-toolchain
cd keystone
mkdir riscv
cd riscv-gnu-toolchain
./configure --prefix=/home/wang/keystone/riscv
make && make linux
vim ~/.bashrc
export RISCV=/home/wang/keystion/riscv
export PATH=$PATH:$RISCV/bin
source ~/.bashrc
(4)install sdk 
cd sdk
mkdir build
cd build 
cmake .. -DOUTPUT_DIR=$(pwd)/../lib
make 
make install 
vim ~/.bashrc
export KEYSTONE_SDK_DIR=/home/wang/keystone/sdk
source ~/.bashrc
(5)clone the runtime
./sdk/scripts/init.sh --runtime eyrie --force
but i meet the problem, i don't known if it will affect the keystone.

Cloning into '/home/wang/keystone/sdk/rts/eyrie'...
remote: Enumerating objects: 102, done.
remote: Counting objects: 100% (102/102), done.
remote: Compressing objects: 100% (68/68), done.
remote: Total 514 (delta 52), reused 65 (delta 32), pack-reused 412
Receiving objects: 100% (514/514), 157.16 KiB | 92.00 KiB/s, done.
Resolving deltas: 100% (336/336), done.
Note: checking out 'f9c2073'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at f9c2073 Specify virtual addresses for SM attestation reports (#25)

(6) make fu540 
cd keystone
mkdir build
cd build
cmake .. -DLINUX_SIFIVE=y
make 
make image
(6)test
./scripts/run-qemu.sh
but meet

1.687435] t5 : ffffffe000cc0940 t6 : ffffffe000cc0140
[ 1.687706] sstatus: 0000000000000120 sbadaddr: ffffffd004000000 scause: 000000000000000d
[ 1.688627] ---[ end trace b4688d94a9846d98 ]---
[ 1.689114] Kernel panic - not syncing: Attempted to kill init! exitcode=0x0000000b
[ 1.689615] ---[ end Kernel panic - not syncing: Attempted to kill init! exitcode=0x0000000b ]---

Thanks for reply!!!!
best wishes!!!!

**Comment by dkohlbre** [comment] 2020-06-22 17:06
A detached HEAD state is normal, since our submodules checkout to a specific revision and not HEAD.

I'm not sure why you are seeing boot failures, we're also looking at the same issue in https://github.com/keystone-enclave/keystone/issues/192

**Comment by dayeol** [comment] 2020-06-23 08:05
I was able to reproduce this issue. 
I suspect the recent changes to the CMakeFiles.txt 
https://github.com/keystone-enclave/keystone/commit/32122e9195f9c302b6670ecf7ad7816d33a092e0

With the new variable, riscv-pk patches are not correctly applied. 
I'll let you know once it's fixed.

**Comment by dayeol** [comment] 2020-06-23 08:19
To temporarily fix the issue, try following commands: 

```
cd riscv-pk
patch --forward -p0 < ../patches/riscv-pk/riscv-pk.sifive.patch
cd ..
```

**Comment by wangaixue** [comment] 2020-06-23 13:28
Thank you very much for your answers @dkohlbre @dayeol . The problem has been solved in qemu and sifive platform.
best wishes ！！！

**Comment by dayeol** [comment] 2020-06-24 17:07
Fixed in dev. Closing

**Closed by dayeol** 2020-06-24 17:07 UTC
Labels: Bug
