### ISSUE TITLE
Ethernet on HiFive Unleashed not working

### ISSUE THREAD

**Issue by thechristschn** [keystone-enclave/keystone#147] opened 2020-02-14 13:23 UTC
**Describe the bug**
The Kernel fails to initialize the network interface on the HiFive Unleashed board. After boot is completed, there is no eth0 interface, only lo and sit0.

Left led on the network interface is flashing, so the link seems to be up. But I can't use it.

**Build Failure**
No build failures. Using master branch from this and keystone/freedom-u540-c000-bootloader repository.

**Screenshots or Error Log**
Error message during boot:
`macb 10090000.ethernet: failed to get macb_clk (-517)`

**Additional context**
Full boot log:
```SiFive FSBL:       2020-01-29-767b856                                                           
Using FSBL DTB                                                                           
HiFive-U serial #: 00000xxx                                                       
Loading boot payload................................                     
                                                                           
bbl loader                                                                      
Relocated DTB from 00000000ffe00000 to 0000000083000000
                                                                  
                SIFIVE, INC.                                                                                  
                                                                            
         5555555555555555555555555                                                                                                              
        5555                   5555                                                     
       5555                     5555                                                   
      5555                       5555                   
     5555       5555555555555555555555                                
    5555       555555555555555555555555                                                                                                                        
   5555                             5555                                   
  5555                               5555                    
 5555                                 5555                                                         
5555555555555555555555555555          55555                                          
 55555           555555555           55555                                 
   55555           55555           55555                   
     55555           5           55555                                   
       55555                   55555                                            
         55555               55555                                                                                            
           55555           55555                                                              
             55555       55555                                 
               55555   55555                                
                 555555555                   
                   55555                                            
                     5                                           
                                                                                                                  
           SiFive RISC-V Core IP                                         
ng smainitializiinitializiinitializilizing sm                                      
                                                                                        
ngng sm
iniinitialize sm
tialid sm
tzneidn ismi
 itialailziezded[  ssmm

    0.000000] OF: fdt: Ignoring memory range 0x80000000 - 0x80200000
[    0.000000] Linux version 5.3.0-dirty (christian@localhost) (gcc version 7.2.0 (GCC)) #3 SMP Fri Feb 14 13:16:29 CET 2020
[    0.000000] earlycon: sbi0 at I/O port 0x0 (options '')
[    0.000000] printk: bootconsole [sbi0] enabled
[    0.000000] initrd not found or empty - disabling initrd
[    0.000000] Zone ranges:
[    0.000000]   DMA32    [mem 0x0000000080200000-0x00000000ffffffff]
[    0.000000]   Normal   empty                                      
[    0.000000] Movable zone start for each node 
[    0.000000] Early memory node ranges                                                         
[    0.000000]   node   0: [mem 0x0000000080200000-0x00000000ffffffff]                   
[    0.000000] Initmem setup node 0 [mem 0x0000000080200000-0x00000000ffffffff]   
[    0.000000] cma: Reserved 1024 MiB at 0x00000000be000000              
[    0.000000] software IO TLB: mapped [mem 0xba000000-0xbe000000] (64MB)  
[    0.000000] CPU with hartid=0 is not available                               
[    0.000000] CPU with hartid=0 is not available      
[    0.000000] elf_hwcap is 0x112d                                
[    0.000000] percpu: Embedded 18 pages/cpu s34520 r8192 d31016 u73728                                       
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 516615
[    0.000000] Kernel command line: console=hvc earlycon=sbi cma=1024M@0-4G                                                                     
[    0.000000] Dentry cache hash table entries: 262144 (order: 9, 2097152 bytes, linear)
[    0.000000] Inode-cache hash table entries: 131072 (order: 8, 1048576 bytes, linear)
[    0.000000] Sorting __ex_table...                    
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] Memory: 934892K/2095104K available (6007K kernel code, 382K rwdata, 1907K rodata, 4997K init, 307K bss, 111636K reserved, 1048576K cma-reserved)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=4, Nodes=1  
[    0.000000] rcu: Hierarchical RCU implementation.         
[    0.000000] rcu:     RCU restricting CPUs from NR_CPUS=8 to nr_cpu_ids=4.                       
[    0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 25 jiffies.
[    0.000000] rcu: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=4
[    0.000000] NR_IRQS: 0, nr_irqs: 0, preallocated irqs: 0
[    0.000000] plic: mapped 53 interrupts with 4 handlers for 9 contexts.
[    0.000000] riscv_timer_init_dt: Registering clocksource cpuid [0] hartid [1]
[    0.000000] clocksource: riscv_clocksource: mask: 0xffffffffffffffff max_cycles: 0x1d854df40, max_idle_ns: 3526361616960 ns
[    0.000006] sched_clock: 64 bits at 1000kHz, resolution 1000ns, wraps every 2199023255500ns
[    0.008505] Console: colour dummy device 80x25              
[    0.012791] printk: console [hvc0] enabled               
[    0.012791] printk: console [hvc0] enabled
[    0.020930] printk: bootconsole [sbi0] disabled                  
[    0.020930] printk: bootconsole [sbi0] disabled               
[    0.029981] Calibrating delay loop (skipped), value calculated using timer frequency.. 2.00 BogoMIPS (lpj=4000)
[    0.040032] pid_max: default: 32768 minimum: 301                      
[    0.044874] Mount-cache hash table entries: 4096 (order: 3, 32768 bytes, linear)
[    0.052102] Mountpoint-cache hash table entries: 4096 (order: 3, 32768 bytes, linear)
[    0.061583] rcu: Hierarchical SRCU implementation.
[    0.066043] smp: Bringing up secondary CPUs ...
[    0.071696] smp: Brought up 1 node, 4 CPUs
[    0.075893] devtmpfs: initialized
[    0.080904] random: get_random_u32 called from bucket_table_alloc.isra.10+0x4e/0x15c with crng_init=0
[    0.089682] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 7645041785100000 ns
[    0.099084] futex hash table entries: 1024 (order: 4, 65536 bytes, linear)
[    0.162942] NET: Registered protocol family 16                                                                           
[    0.182206] vgaarb: loaded                             
[    0.184465] SCSI subsystem initialized        
[    0.188232] usbcore: registered new interface driver usbfs
[    0.193380] usbcore: registered new interface driver hub
[    0.198678] usbcore: registered new device driver usb             
[    0.204344] clocksource: Switched to clocksource riscv_clocksource
[    0.215924] NET: Registered protocol family 2
[    0.220099] tcp_listen_portaddr_hash hash table entries: 1024 (order: 2, 16384 bytes, linear)
[    0.228086] TCP established hash table entries: 16384 (order: 5, 131072 bytes, linear)
[    0.236462] TCP bind hash table entries: 16384 (order: 6, 262144 bytes, linear)
[    0.244020] TCP: Hash tables configured (established 16384 bind 16384)
[    0.250176] UDP hash table entries: 1024 (order: 3, 32768 bytes, linear)
[    0.256578] UDP-Lite hash table entries: 1024 (order: 3, 32768 bytes, linear)
[    0.263878] NET: Registered protocol family 1       
[    0.268492] RPC: Registered named UNIX socket transport module.
[    0.273833] RPC: Registered udp transport module.                                                          
[    0.278507] RPC: Registered tcp transport module.                        
[    0.283194] RPC: Registered tcp NFSv4.1 backchannel transport module.                                                                        
[    0.289625] PCI: CLS 0 bytes, default 64                                             
[    0.338522] workingset: timestamp_bits=62 max_order=19 bucket_order=0               
[    0.352245] NFS: Registering the id_resolver key type
[    0.356548] Key type id_resolver registered                        
[    0.360749] Key type id_legacy registered                                                                                                                   
[    0.364692] nfs4filelayout_init: NFSv4 File Layout Driver Registering...
[    0.371559] 9p: Installing v9fs 9p2000 file system support
[    0.377172] NET: Registered protocol family 38                                                  
[    0.381299] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 253)  
[    0.388647] io scheduler mq-deadline registered                         
[    0.393158] io scheduler kyber registered               
[    0.435331] Serial: 8250/16550 driver, 4 ports, IRQ sharing disabled  
[    0.442173] [drm] radeon kernel modesetting enabled.                         
[    0.455164] loop: module loaded                                                                                            
[    0.458223] sifive_spi 10040000.spi: mapped; irq=39, cs=1                                  
[    0.463435] sifive_spi 10041000.spi: mapped; irq=40, cs=4   
[    0.468674] sifive_spi 10050000.spi: mapped; irq=41, cs=1
[    0.474204] libphy: Fixed MDIO Bus: probed
[    0.478303] macb 10090000.ethernet: failed to get macb_clk (-517)
[    0.484037] e1000e: Intel(R) PRO/1000 Network Driver - 3.2.6-k
[    0.489656] e1000e: Copyright(c) 1999 - 2015 Intel Corporation.                                                
[    0.495655] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    0.502074] ehci-pci: EHCI PCI platform driver                                  
[    0.506528] ehci-platform: EHCI generic platform driver                              
[    0.511825] ohci_hcd: USB 1.1 'Open' Host Controller (OHCI) Driver
[    0.517873] ohci-pci: OHCI PCI platform driver 
[    0.522330] ohci-platform: OHCI generic platform driver
[    0.527913] usbcore: registered new interface driver uas
[    0.532849] usbcore: registered new interface driver usb-storage                                     
[    0.538923] mousedev: PS/2 mouse device common for all mice                                                
[    0.577302] mmc_spi spi2.0: SD/MMC host mmc0, no DMA, no WP, no poweroff, cd polling
[    0.584446] usbcore: registered new interface driver usbhid                                                              
[    0.589826] usbhid: USB HID core driver                
[    0.594544] NET: Registered protocol family 10
[    0.598995] Segment Routing with IPv6                     
[    0.601972] sit: IPv6, IPv4 and MPLS over IPv4 tunneling driver
[    0.608371] NET: Registered protocol family 17                           
[    0.612434] 9pnet: Installing 9P2000 support                                                                                                 
[    0.616524] Key type dns_resolver registered                                         
[    0.621365] macb 10090000.ethernet: failed to get macb_clk (-517)                            
[    0.626936] macb 10090000.ethernet: failed to get macb_clk (-517)                     
[    0.646921] Freeing unused kernel memory: 4996K                                
[    0.650686] This architecture does not have kernel memory protection.                                                                                       
[    0.657106] Run /init as init process                                   
Starting syslogd: OK                                                            
Starting klogd: OK                                                                                 
Running sysctl: OK                                                                   
Initializing random number generator... [    0.719749] random: dd: uninitialized urandom read (512 bytes read)
done.                                                      
Starting network: Waiting for interface eth0 to appear[    0.769078] mmc0: host does not support reading read-only switch, assuming write-enable
[    0.776343] mmc0: new SDHC card on SPI                                       
[    0.782459] mmcblk0: mmc0:0000 SC32G 29.7 GiB                                                                              
.....[    6.242525]  mmcblk0: p1 p2 p3                                                        
[    6.245700] macb 10090000.ethernet: failed to get macb_clk (-517)
.......... timeout!                                         
run-parts: /etc/network/if-pre-up.d/wait_iface: exit status 1              
FAIL                                                                
Starting dropbear sshd: [   15.814404] random: dropbear: uninitialized urandom read (32 bytes read)
OK                                                                                                                
                                                                         
Welcome to Buildroot                                                               
buildroot login:
```

**Comment by dayeol** [comment] 2020-02-28 00:22
Sorry for late reply. I had some time to check this and reproduce.
Probably this is related to the following issue: https://forums.sifive.com/t/network-driver-failure-clock-issue/2971 but I could not figure out the cause.
It's likely related to device tree. When we bump the latest upstream Linux, there were issues where the old device tree doesn't match with the newer Linux. We worked around the issue by hacking the kernel to bypass some of the checks and boot, but I guess that was not a complete fix.
I will look into this to see if there is an easy fix. Otherwise, we may need to move forward to OpenSBI-based implementation. 
Probably the same reason for #148  as well.

**Comment by dayeol** [comment] 2020-10-21 22:03
This will be fixed with the OpenSBI port.
The cause was the wrong device tree being passed.

**Comment by dayeol** [comment] 2021-03-02 22:25
Resolved

**Closed by dayeol** 2021-03-02 22:25 UTC
Labels: Help Wanted
